project_name: 'SuperGamer'
game_name: "Sid Meier's Civilization V (DX9)"
run_name: 'ui-tars - run0'
close_explore: True
close_reflexion: False
close_reset: True
is_base: True

result_path: 'results'

teacher_type: 'Random' # Human or AI or Random

brain:
  base_model: 'UI_TARS' # gpt-4o or claude-3-7-sonnet-20250219 
  evaluate_model: 'gpt-4o'

  uct_c: 2.0
  uct_threshold: 0.0

detector:
  sam_weights: 'weights/sam_vit_b_01ec64.pth'  # sam_vit_b_01ec64 or sam_vit_b_4b8939
  sam_type: 'vit_b'     # vit_h or vit_b
  clip_model: 'ViT-B/32' # ViT-B/32, ViT-B/16, ViT-L/14, RN50

eye:
  width: 1280
  height: 800

long_memory:
  sim_threshold: 0.9