project_name: 'SuperGamer'
game_name: 'Slay the Spire'
run_name: 'claude - omni - blip2'
close_explore: False
close_reflexion: False
close_reset: False
is_base: False

result_path: 'results'

teacher_type: 'human-mouse' # Human or AI or Random

brain:
  base_model: 'claude-3-7-sonnet-20250219' # gpt-4o or claude-3-7-sonnet-20250219
  evaluate_model: 'gpt-4o'

  uct_c: 5.0
  uct_threshold: 0.0

detector:
  type: 'omni'  # 'sam' or 'omni'
  # config for sam
  sam:
    sam_weights: 'weights/sam_vit_b_01ec64.pth'
    sam_type: 'vit_b'
  # config for omni
  omni:
    som_model_path: 'weights/icon_detect/model.pt'
    caption_model_name: 'blip2'  # BLIP-2 for stable captioning
    caption_model_path: 'Salesforce/blip2-opt-2.7b'  # BLIP-2 HuggingFace repo
    BOX_TRESHOLD: 0.35
    iou_threshold: 0.4
    text_overlap_threshold: 0.25
  # general
  clip_model: 'ViT-B/32' # ViT-B/32, ViT-B/16, ViT-L/14, RN50

eye:
  width: 1280
  height: 720

long_memory:
  sim_threshold: 0.9